# Generated by Django 3.2.8 on 2021-10-14 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyPesaPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('amount', models.FloatField(null=True)),
                ('msisdn', models.CharField(max_length=50, null=True)),
                ('mpesa_transaction_id', models.CharField(max_length=50, null=True)),
                ('tiny_pesa_id', models.UUIDField(null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Successful'), (1, 'Failed')], null=True)),
            ],
            options={
                'swappable': 'TINYPESA_PAYMENT_MODEL',
            },
        ),
    ]
